apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mysql-kustomization
  namespace: mysql
resources:
  - mysql-namespace.yaml
  - mysql-deployment.yaml
  - mysql-secrets.yaml
  - mysql-storage.yaml
  - mysql-ingress.yaml
